name: flutter_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.2
  go_router: ^16.2.4
  dio: ^5.5.0
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  url_launcher: ^6.3.2
  shared_preferences: ^2.3.2
  ar_flutter_plugin: ^0.7.3
  path_provider: ^2.1.5
  firebase_ai: ^3.3.0
  syncfusion_flutter_pdfviewer: ^31.1.23
  firebase_storage: ^13.0.3
  http: ^1.5.0
  share_plus: ^12.0.0
  file_saver: ^0.3.1
  open_filex: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/XT1/
    - lib/images/XT2/
    - lib/images/XT3/
    - lib/images/XT4/
    - lib/images/XT5/
    - lib/images/XT6/
    - lib/images/XT7/
    - lib/images/general/
    - lib/json/
    - lib/3Dmodels/XT1/
    - lib/3Dmodels/XT2/
    - lib/3Dmodels/XT3/
    - lib/3Dmodels/XT4/
    - lib/3Dmodels/XT5/
    - lib/3Dmodels/XT6/
    - lib/3Dmodels/XT7/
  fonts:
    - family: ABBvoice
      fonts:
        - asset: lib/resources/ABBvoice_Lt.ttf
          weight: 300
        - asset: lib/resources/ABBvoice_Rg.ttf
          weight: 400
        - asset: lib/resources/ABBvoice_Md.ttf
          weight: 500
        - asset: lib/resources/ABBvoice_Bd.ttf
          weight: 700

dependency_overrides:
  permission_handler: ^12.0.1
  permission_handler_android: ^13.0.1
  permission_handler_platform_interface: ^4.3.0

