// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSimQSiWFrEKLO23v-IEgNGDan_YBtNQ8',
    appId: '1:317501248625:web:c70ded9c2455f24468b7d0',
    messagingSenderId: '317501248625',
    projectId: 'tesi-2025-a0d0c',
    authDomain: 'tesi-2025-a0d0c.firebaseapp.com',
    storageBucket: 'tesi-2025-a0d0c.firebasestorage.app',
    measurementId: 'G-24RNQF7XSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBimM38pUAyLfGQbYOzKgIC0f5R0nqOc8',
    appId: '1:317501248625:android:1ddfc53fb76770ad68b7d0',
    messagingSenderId: '317501248625',
    projectId: 'tesi-2025-a0d0c',
    storageBucket: 'tesi-2025-a0d0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjsmzUCsNBn3VPaDUcLMPb0YvErm2Rjco',
    appId: '1:317501248625:ios:de39ab121775eae068b7d0',
    messagingSenderId: '317501248625',
    projectId: 'tesi-2025-a0d0c',
    storageBucket: 'tesi-2025-a0d0c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjsmzUCsNBn3VPaDUcLMPb0YvErm2Rjco',
    appId: '1:317501248625:ios:de39ab121775eae068b7d0',
    messagingSenderId: '317501248625',
    projectId: 'tesi-2025-a0d0c',
    storageBucket: 'tesi-2025-a0d0c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSimQSiWFrEKLO23v-IEgNGDan_YBtNQ8',
    appId: '1:317501248625:web:45dd21462d6003ba68b7d0',
    messagingSenderId: '317501248625',
    projectId: 'tesi-2025-a0d0c',
    authDomain: 'tesi-2025-a0d0c.firebaseapp.com',
    storageBucket: 'tesi-2025-a0d0c.firebasestorage.app',
    measurementId: 'G-BR36GTXT78',
  );
}
